import Head from 'next/head'


export default function Home() {
	return (
		<div>
			<Head>
				<title>Hosted using amazon s3 buckets</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>App</main>
		</div>
	)
}
